### ISSUE TITLE
Looking up the game's registry key causes an error and crashes the app at startup

### ISSUE THREAD

**Issue by Mgamerz** [Mgamerz/me3modmanager#3]
Using the JNA Registry key lookup causes some clients apps to crash, throwing a java.lang.error saying ERROR_SUCCESS. This is not caught, but the error being thrown does not make sense.

Related issue  java-native-access/jna#517

Stack trace:

```
Exception in thread "main" java.lang.Error: The operation completed successfully
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171)
at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
at com.sun.jna.Library$Handler.<init>(Library.java:147)
at com.sun.jna.Native.loadLibrary(Native.java:412)
at com.sun.jna.platform.win32.Advapi32.<clinit>(Advapi32.java:47)
at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:549)
at com.me3tweaks.modmanager.ModManagerWindow.getInitialBiogameDirText(ModManagerWindow.java:1476)
at com.me3tweaks.modmanager.ModManagerWindow.setupWindow(ModManagerWindow.java:468)
at com.me3tweaks.modmanager.ModManagerWindow.initializeWindow(ModManagerWindow.java:193)
at com.me3tweaks.modmanager.ModManagerWindow.<init>(ModManagerWindow.java:130)
at com.me3tweaks.modmanager.ModManager.main(ModManager.java:312)
```

**Comment by Mgamerz** [comment]
Fixed in Build 45 by using JNA 4.2.
